# Generated by Django 5.0.1 on 2024-01-05 11:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0006_paciente_atualizado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendado_para', models.DateTimeField(help_text='data marcada para o atendimento.', verbose_name='data marcada para o atendimento.')),
                ('criado_em', models.DateTimeField(default=datetime.datetime(2024, 1, 5, 11, 29, 2, 402592, tzinfo=datetime.timezone.utc), help_text='data de criação do registro de agendamento.', verbose_name='data de criação.')),
                ('atualizado_em', models.DateTimeField(default=datetime.datetime(2024, 1, 5, 11, 29, 2, 402611, tzinfo=datetime.timezone.utc), help_text='data da ultima atualizacao do registro de agendamento.', verbose_name='data de atualização.')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
