# Generated by Django 5.0.1 on 2024-01-05 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='data da ultima atualizacao do registro de agendamento.', verbose_name='data de atualização.'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='data de criação do registro de agendamento.', verbose_name='data de criação.'),
        ),
    ]
