# Generated by Django 5.0.1 on 2024-01-05 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0002_alter_agendamento_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RaioX', 'Exame do tipo raio_x.'), ('Tomografia', 'Exame do tipo tomografia.')], help_text='Expecificação do tipo de exame.', max_length=10, verbose_name='Tipo de exame.')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação do registro de exame.', verbose_name='Data de criação.')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendamento')),
            ],
        ),
    ]
