# Generated by Django 5.0.1 on 2024-01-04 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencial', models.TextField(choices=[('Deficiente', 'pessoa com deficiência física.'), ('PessoaIdosa', 'idosos com idade igual ou superior a sessenta e cinco anos.'), ('Gestante', 'mães em periodo de gestação.'), ('Lactante', 'mães com filho(a) recém nascido.'), ('CriancaDeColo', 'pessoas acompanhadas por crianças de colo.'), ('NaoPreferencialpessoa sem condicao preferencial.', 'Nao Preferencial')], default='NaoPreferencialpessoa sem condicao preferencial.', help_text='Condição preferencial de atendimento.', verbose_name='Condição preferencial')),
                ('sexo', models.CharField(choices=[('H', 'Homen'), ('M', 'Mulher')], default='H', help_text='genero sexual', max_length=1, verbose_name='genero sexual')),
                ('status', models.CharField(choices=[('Aguardando', 'Paciente aguardando atendimento.'), ('Cancelado', 'Consulta cancelada pelo paciente ou pelo sistema.'), ('EmAtendimento', 'Paciente em atendimento médico.'), ('Concluído', 'Consulta concluída.')], default='Aguardando', help_text='gerencia status de atendimento.', max_length=15, verbose_name='status do atendimento.')),
                ('idade', models.IntegerField(help_text='Idade do paciente', verbose_name='Idade do paciente')),
                ('criado_em', models.DateField(default=datetime.date(2024, 1, 4), help_text='data de criação/inicio do paciente no sistema.', verbose_name='data de entrada do paciente.')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
