# Generated by Django 5.0.1 on 2024-01-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nome',
            field=models.TextField(default='', help_text='nome do paciente.', verbose_name='nome do paciente.'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='preferencial',
            field=models.TextField(choices=[('NaoPreferencialpessoa sem condicao preferencial.', 'Nao Preferencial'), ('Deficiente', 'pessoa com deficiência física.'), ('PessoaIdosa', 'idosos com idade igual ou superior a sessenta e cinco anos.'), ('Gestante', 'mães em periodo de gestação.'), ('Lactante', 'mães com filho(a) recém nascido.'), ('CriancaDeColo', 'pessoas acompanhadas por crianças de colo.')], default='NaoPreferencialpessoa sem condicao preferencial.', help_text='Condição preferencial de atendimento.', verbose_name='Condição preferencial'),
        ),
    ]
