# Generated by Django 5.0.1 on 2024-01-04 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='data da ultima atualização realizada no registro do paciente.', verbose_name='data de atualização.'),
        ),
    ]
